defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
propagationMethod: all
siteSettings:
  6e2d25df-7769-4b54-ab25-4bb36302500d: # Recipes
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
