field: 90d32663-4f7e-492f-a927-a463a2e04112 # Process
fieldLayouts:
  8835f355-a012-432b-88f1-d1cd576c161a:
    tabs:
      -
        elements:
          -
            fieldUid: a0199e8b-03c6-4a1d-98d3-490426d22984 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b97dd982-ca17-4db0-bcc2-3a62893dc8f7 # Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf3baef0-f6b7-44ce-af40-6764fe8d10e3 # Estimated Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a0199e8b-03c6-4a1d-98d3-490426d22984: # Headline
    columnSuffix: tqnkabzo
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b97dd982-ca17-4db0-bcc2-3a62893dc8f7: # Instructions
    columnSuffix: gfkswmpy
    contentColumnType: text
    fieldGroup: null
    handle: instructions
    instructions: ''
    name: Instructions
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cf3baef0-f6b7-44ce-af40-6764fe8d10e3: # Estimated Time
    columnSuffix: jzjqphlf
    contentColumnType: integer(10)
    fieldGroup: null
    handle: estimatedTime
    instructions: ''
    name: 'Estimated Time'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: min
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: combine
name: Combine
sortOrder: 1
