field: 90d32663-4f7e-492f-a927-a463a2e04112 # Process
fieldLayouts:
  b570e96c-64d6-4927-9068-80d711bdd075:
    tabs:
      -
        elements:
          -
            fieldUid: 19ae9336-f0f1-4ceb-b8d1-a1937d796689 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ef824be9-843f-4955-b729-9f7439695f31 # Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 192710f4-bae5-448e-9bc1-da6413aac4af # Estimated Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  19ae9336-f0f1-4ceb-b8d1-a1937d796689: # Headline
    columnSuffix: rnnovokj
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  192710f4-bae5-448e-9bc1-da6413aac4af: # Estimated Time
    columnSuffix: fwdbopkj
    contentColumnType: integer(10)
    fieldGroup: null
    handle: estimatedTime
    instructions: ''
    name: 'Estimated Time'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: min
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ef824be9-843f-4955-b729-9f7439695f31: # Instructions
    columnSuffix: yxpqtfjv
    contentColumnType: text
    fieldGroup: null
    handle: instructions
    instructions: ''
    name: Instructions
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: cook
name: Cook
sortOrder: 2
