field: 90d32663-4f7e-492f-a927-a463a2e04112 # Process
fieldLayouts:
  ccd99896-ec5a-4f68-9c75-2c8eb1dff071:
    tabs:
      -
        elements:
          -
            fieldUid: 2add55ba-96e4-4f07-991c-f0aa3835d16d # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eac80011-368f-43fb-a615-f08ed89e010b # Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 00286cc1-f7d3-4329-825e-c4fbe40c1ee6 # Estimated Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2add55ba-96e4-4f07-991c-f0aa3835d16d: # Headline
    columnSuffix: sxbtlukc
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  00286cc1-f7d3-4329-825e-c4fbe40c1ee6: # Estimated Time
    columnSuffix: mgvtihep
    contentColumnType: integer(10)
    fieldGroup: null
    handle: estimatedTime
    instructions: ''
    name: 'Estimated Time'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: none
      size: null
      suffix: min
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  eac80011-368f-43fb-a615-f08ed89e010b: # Instructions
    columnSuffix: ivjcmmfz
    contentColumnType: text
    fieldGroup: null
    handle: instructions
    instructions: ''
    name: Instructions
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: prepare
name: Prepare
sortOrder: 3
