columnSuffix: null
contentColumnType: string
fieldGroup: bcb78bb0-43ec-420a-b880-eb82f0770ef0 # Recipes
handle: ingredientList
instructions: ''
name: 'Ingredient List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_ingredientlist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
